#!/usr/bin/env python
import os

from core.routes import Route
from core.args import Args
from core.db.DB import DB

from app.controllers.db.MigrateController import MigrateController
from app.controllers.db.SeedController import SeedController

from app.controllers.AnimalClassController import AnimalClassController
from app.controllers.KnowledgeController import KnowledgeController
from app.controllers.CharacteristicController import CharacteristicController
from app.controllers.PropertyController import PropertyController
from app.controllers.FactController import FactController
from app.controllers.RuleController import RuleController
from app.controllers.PropertyFactController import PropertyFactController
from app.controllers.PropertyRuleController import PropertyRuleController

from app.controllers.AllController import AllController



DB.app_path = os.path.dirname(os.path.abspath(__file__))

Args.init()

Route.add('store.animal_class', [AnimalClassController, 'store'])
Route.add('show.animal_class', [AnimalClassController, 'show'])
Route.add('all.animal_class', [AnimalClassController, 'all'])

Route.add('store.knowledge', [KnowledgeController, 'store'])
Route.add('show.knowledge', [KnowledgeController, 'show'])
Route.add('all.knowledge', [KnowledgeController, 'all'])

Route.add('store.characteristic', [CharacteristicController, 'store'])
Route.add('show.characteristic', [CharacteristicController, 'show'])
Route.add('all.characteristic', [CharacteristicController, 'all'])

Route.add('store.property', [PropertyController, 'store'])
Route.add('show.property', [PropertyController, 'show'])
Route.add('all.property', [PropertyController, 'all'])

Route.add('store.fact', [FactController, 'store'])
Route.add('show.fact', [FactController, 'show'])
Route.add('all.fact', [FactController, 'all'])

Route.add('store.rule', [RuleController, 'store'])
Route.add('show.rule', [RuleController, 'show'])
Route.add('all.rule', [RuleController, 'all'])

Route.add('store.property_act', [PropertyFactController, 'store'])
Route.add('show.property_act', [PropertyFactController, 'show'])
Route.add('all.property_act', [PropertyFactController, 'all'])

Route.add('store.property_rule', [PropertyRuleController, 'store'])
Route.add('show.property_rule', [PropertyRuleController, 'show'])
Route.add('all.property_rule', [PropertyRuleController, 'all'])

Route.add('all', [AllController, 'run'])

Route.add('seed', [SeedController, 'run'])
Route.add('migrate', [MigrateController, 'run'])


Route.exec()
